apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-prueba
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: lumonidy.studio
    http:
      paths:
      - backend:
          service:
            name: golang-service
            port:
              number: 80
        pathType: Prefix
        path: /api/admin
  - host: www.lumonidy.studio
    http:
      paths:
      - backend:
          service:
            name: golang-service
            port:
              number: 80
        pathType: Prefix
        path: /api/admin